name: Generate Stats Images

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Checkout history branch
      run: |
        git config --global user.name "jstrieb/github-stats"
        git config --global user.email "github-stats[bot]@jstrieb.github.io"
        # Push generated files to the generated branch
        git checkout generated || git checkout -b generated
        git merge master

    - uses: mlugg/setup-zig@v2
      with:
        version: 0.15.2

    - name: Build
      run: |
        zig build --release

    - name: Generate images
      run: |
        ./zig-out/bin/github_stats
      env:
        API_KEY: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED_REPOS: ${{ secrets.EXCLUDED_REPOS }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}

    - name: Commit to the repo
      run: |
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push
