name: Build Release Binaries

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29  # v2 tag
      with:
        version: 0.15.2

    - name: Build
      run: |
        zig build release

    - name: Upload Release Artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TAG: ${{ github.ref_name }}
      run: |
        (
          cd zig-out/bin/
          gh release create \
            "${TAG}" \
            --title "${TAG} Release" \
            *
        )
